#!/bin/bash 

readarray -t array <<<"$(pactl list sink-inputs | ag '№|media.name|Громкость' | sed -e 's#Вход аудиоприёмника №##' | sed -e 's#.* \([0-9][0-9]*\)%.*#\1#' | cut -d "\"" -f2)"

if [ -z "${array[*]}" ]; then
    echo "[]"
    exit 0
fi

json=""
for (( j=0; j<${#array[@]}; j+=3 )); do
	name="${array[$j+2]}"
    if [ "$name" = "playback" ]; then
        continue
    fi
    name=$(echo "$name" | sed 's#\\#|#g' | sed 's/"/\\"/g')
	name_buf=$(echo "$name" | iconv -t latin1)
	if [[ $? == 0 ]]; then
		name=$(echo "$name_buf" | iconv -f cp1251)
	fi
    printf -v subjson '{"num": "%d", "value": "%d", "name": "%s"},' "${array[$j]}" "${array[$j+1]}" "$name"
    json+="$subjson"
done

echo "[${json%,}]"
