version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[var]
  ssh = "/media/artemiy/3fe68576-1a13-42fc-94c3-a6e34f218cf4"

[palette]
  cyan = 'cyan'
  darkcyan = '#00abab'
  gray = '#888888'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
	type = "time"
	style = "plain"
	foreground = "p:darkcyan"
    template = '{{ if .Env.TMUX }} {{ .CurrentDate | date .Format }}{{ else }}{{ replaceP .Var.ssh .PWD "󱊟 SSH" }}{{ end }}'

	[properties]
	time_format = "15:04:05"

    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:gray'
    background = 'transparent'
    template = '󰚭 {{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 1000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    template = ''

[transient_prompt]
  background = 'transparent'
  template = '<p:cyan,transparent> {{ now | date "15:04:05" }}</> ❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯ '

