console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  cyan = 'cyan'
  darkcyan = '#00abab'
  gray = '#888888'

[var]
  ssd = '/media/artemiy/3fe68576-1a13-42fc-94c3-a6e34f218cf4'
  time = '15:04:05'

[secondary_prompt]
  template = '❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '<p:cyan,transparent> {{ now | date .Var.time }}</> ❯ '
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ if .Env.TMUX }} {{ .CurrentDate | date .Format }}{{ else }}{{ replaceP .Var.ssd .PWD "󱊟 SSD" }}{{ end }}'
    foreground = 'p:darkcyan'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '󰚭 {{ .FormattedMs }}'
    foreground = 'p:gray'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 1000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ''
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
