require("core.plugins")
require("core.config")

-- Plugins
require("plugins.mason")
require("plugins.gitsigns")
require("plugins.treesitter")
require("plugins.comment")
require("plugins.tree")
require("plugins.colors")
require("plugins.comment")
require("plugins.whichkey")
require("plugins.bufferline")
require("plugins.nullls")
require("plugins.autopairs")
require("plugins.cmp")
require("plugins.lspconfig")
require("plugins.tabnine")
require("plugins.noice")
require("plugins.terminal")
require("plugins.devicons")
require("plugins.lspcolors")
require("plugins.telescope")
require("plugins.lualine")
require("plugins.increname")
require("plugins.barbartabs")
